# Generated by Django 5.2.7 on 2026-01-14 21:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('culoare_identificare', models.CharField(default='#000000', help_text='Cod HEX culoare (ex: #FF0000)', max_length=20)),
                ('descriere', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id_furnizor', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=155)),
                ('tara_origine', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Furnizori',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('data_creare', models.DateField()),
                ('tara_origine', models.CharField(max_length=100)),
                ('fondator', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Marci',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id_motor', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=100)),
                ('capacitate_cc', models.IntegerField()),
                ('consum', models.FloatField()),
                ('putere_cp', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Motoare',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, help_text='Număr de telefon.', max_length=15)),
                ('adresa', models.CharField(blank=True, help_text='Adresa completă.', max_length=100)),
                ('oras', models.CharField(blank=True, max_length=50)),
                ('judet', models.CharField(blank=True, max_length=50)),
                ('newsletter', models.BooleanField(default=False, help_text='Abonează-te la noutăți.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Piesa',
            fields=[
                ('id_piesa', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=150)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garantie_luni', models.IntegerField()),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_moto.furnizor')),
            ],
            options={
                'verbose_name_plural': 'Piese',
            },
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id_motocicleta', models.AutoField(primary_key=True, serialize=False)),
                ('serie_sasiu', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('an_fabricatie', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_introducere', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_moto.categorie')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_moto.marca')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_moto.motor')),
                ('piese', models.ManyToManyField(blank=True, to='magazin_moto.piesa')),
            ],
            options={
                'verbose_name_plural': 'Motociclete',
            },
        ),
    ]
