# Generated by Django 5.2.7 on 2026-01-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_moto', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateField()),
                ('subiect', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('discount', models.IntegerField(help_text='Procent reducere (ex: 15)')),
                ('cod_promo', models.CharField(help_text='Ex: MOTO2024', max_length=20)),
                ('categorii', models.ManyToManyField(blank=True, to='magazin_moto.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_moto.motocicleta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
